apiVersion: v1
kind: Service
metadata:
  name: milyfe-frontend
  namespace: milyfe
  labels:
    app: milyfe-frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: milyfe-frontend
